Name:           perl-Proc-Daemon
Version:        0.23
Release:        1%{?dist}
Summary:        Run Perl program(s) as a daemon process
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Proc-Daemon/
Source0:        http://www.cpan.org/authors/id/A/AK/AKREAL/Proc-Daemon-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Proc::ProcessTable)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module can be used by a Perl program to initialize itself as a daemon
or to execute (exec) a system command as daemon. You can also check the
status of the daemon (alive or dead) and you can kill the daemon.

%prep
%setup -q -n Proc-Daemon-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed May 18 2022 Arne Becker 0.23-1
- Specfile autogenerated by cpanspec 1.78.
